spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: my_user
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true

custom:
  order-activity-time-milliseconds: 600000 # 10 minutes
